name: treetrace_mobile
description: TreeTrace - Panabo City Tree Inventory Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  dio: ^5.4.0
  http: ^1.2.1

  # State management
  provider: ^6.1.2
  flutter_secure_storage: ^9.0.0

  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Image picker
  image_picker: ^1.0.7

  # QR scanner
  mobile_scanner: ^5.1.0

  # Map
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Utilities
  intl: ^0.19.0
  connectivity_plus: ^6.0.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
